### PR TITLE
Bring keywords in line with official TreeSitter guidelines

### PR DESCRIPTION
**Pull request by EleanorNB**
This PR brings in all keywords in the official Zig grammar, and categorises them according to [official TreeSitter guidelines](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#keywords). I had found some inconsistencies and miscategorisations in the standing grammar.

### CODE REVIEW

**Comment by maxxnino** [comment]
Just in case you miss this
(BuildinTypeExpr) is u8,u16,...,f8,f16,...,i8,i16,....

**Comment by EleanorNB** [comment]
Fixed. Awaiting external guidance on placement of coroutine control and defers before I undraft this.

**Comment by maxxnino** [comment]
I think you missed "true" "false" and "="

**Comment by EleanorNB** [comment]
I did miss `true` and `false` so I've added those in, but I didn't touch anything that would have affected `=`. That's not a keyword.

**Comment by maxxnino** [comment]
my bad `AssignOp` already include "="

**Comment by EleanorNB** [comment]
You know what, I don't think I'm going to get any external guidance. I've made the executive decision to move all the coroutine keywords (bar `nosuspend`) into `@keyword.return` but leave the rest where they are. And now we're ready to roll.

**Comment by maxxnino** [comment]
`void` `noreturn` `anyframe` `anyopaque` `anyerror`  are already included in `(BuildinTypeExpr)`. Everything else look really good
```diff
[
-  "void"
-  "noreturn"
  "anytype"
-  "anyframe"
-  "anyopaque"
-  "anyerror"
  (BuildinTypeExpr)
] @type.builtin
```

**Comment by EleanorNB** [comment]
Pushed.

**Comment by maxxnino** [comment]
Thank you. In other to use it in neovim. You have to make a pr in nvim-treesitter repo too

**Pull request merged**
