### PR TITLE
More grammar changes

### PR DESCRIPTION
**Pull request by resolritter**
Those changes are aimed at reducing the number of failures listed in `scripts/known-parsing-failures.txt`

### CODE REVIEW

**Comment by resolritter** [comment]
Moving this to Draft for a while because I might try later

- Get rid of the last failure later
- Include more projects to test e.g. https://github.com/tigerbeetledb/tigerbeetle, https://github.com/zigtools/zls, etc.

**Comment by resolritter** [comment]
As of commit https://github.com/maxxnino/tree-sitter-zig/pull/36/commits/8c2461cdfd1c15214e51f84fc49d40842d756131 there are no more known failures while parsing https://github.com/ziglang/zig.

More projects were added in https://github.com/maxxnino/tree-sitter-zig/blob/8c2461cdfd1c15214e51f84fc49d40842d756131/scripts/test-parsing#L49-L51 and all were similarly parsed without errors.

Obviously, that does not mean that the parser is parsing everything _correctly_, it just means that it's not producing errors. I think we'd be able to gauge its correctness through corpus tests (#25).

**Comment by maxxnino** [comment]
I have experimented with the grammar and have noticed a significant improvement. Thank you for your help! However, this has caused some issues with the existing query, which is a separate issue for the time being.

**Comment by resolritter** [comment]
> I have experimented with the grammar and have noticed a significant improvement.

Thanks for trying it out.

> However, this has caused some issues with the existing query, which is a separate issue for the time being.

It's true that I was not taking queries into account so far. I'll add a test for them as well.

**Comment by resolritter** [comment]
Query testing was added in https://github.com/maxxnino/tree-sitter-zig/pull/36/commits/152951504b43c59492a1bffbad8e9b6b61df12ba. It only tests if the queries can be **compiled** correctly, which they are - so I guess that the issue you're describing is related to something else?

For testing the queries' outputs, I suppose there could be something like the nvim-treesitter highlights + indents tests (see https://github.com/nvim-treesitter/nvim-treesitter/blob/87faf372eb517077cc600c4e653e4fb3252d02ac/tests/query/highlights/gleam/import.gleam for instance). However, that is not something that I intend to add in this PR.

**Pull request merged**
